openapi: 3.1.0
info:
  title: YugabyteDB Aeon REST Access Keys RBAC management API
  description: The YugabyteDB Aeon REST API provides programmatic access to YugabyteDB's fully managed cloud database service. Developers and operators can use it to deploy and manage database clusters, configure read replicas, schedule and execute on-demand backups and restores, manage IP allow lists, and set up monitoring and alerts. Authentication is performed using API keys passed as bearer tokens in the Authorization header. All paths are scoped to an account and project, which can be obtained from the YugabyteDB Aeon UI profile page.
  version: v1
  contact:
    name: Yugabyte Support
    url: https://support.yugabyte.com
  termsOfService: https://www.yugabyte.com/yugabytedb-managed-service-terms/
  x-generated-from: documentation
  x-source-url: https://api-docs.yugabyte.com/docs/managed-apis/
  x-last-validated: '2026-05-03'
servers:
- url: https://cloud.yugabyte.com/api/public/v1
  description: YugabyteDB Aeon Production Server
security:
- bearerAuth: []
tags:
- name: RBAC management
paths:
  /api/v1/customers/{cUUID}/rbac/permissions:
    get:
      description: 'WARNING: This is a preview API that could change.'
      operationId: listPermissions
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - description: Optional resource type to filter permission list
        in: query
        name: resourceType
        schema:
          default: 'null'
          type: string
        example: 'null'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PermissionInfo'
                type: array
              examples:
                ListPermissions200Example:
                  summary: Default listPermissions 200 response
                  x-microcks-default: true
                  value:
                  - permissionValidOnResource: true
                    prerequisitePermissions:
                    - action: CREATE
                      resourceType: UNIVERSE
                    - action: CREATE
                      resourceType: UNIVERSE
                    name: name
                    action: CREATE
                    description: description
                    resourceType: UNIVERSE
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List All the Permissions Available
      tags:
      - RBAC management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/rbac/role:
    get:
      description: 'WARNING: This is a preview API that could change.'
      operationId: listRoles
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - description: Optional role type to filter roles list
        in: query
        name: roleType
        schema:
          default: 'null'
          type: string
        example: 'null'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Role'
                type: array
              examples:
                ListRoles200Example:
                  summary: Default listRoles 200 response
                  x-microcks-default: true
                  value:
                  - customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    permissionDetails:
                      permissionList:
                      - action: CREATE
                        resourceType: UNIVERSE
                      - action: CREATE
                        resourceType: UNIVERSE
                    name: name
                    description: description
                    updatedOn: 2022-12-12 13:07:18+00:00
                    roleType: System
                    createdOn: 2022-12-12 13:07:18+00:00
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List All the Roles Available
      tags:
      - RBAC management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      description: 'WARNING: This is a preview API that could change.'
      operationId: createRole
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleFormData'
            examples:
              CreateRoleRequestExample:
                summary: Default createRole request
                x-microcks-default: true
                value:
                  name: name
                  description: description
                  permissionList:
                  - action: CREATE
                    resourceType: UNIVERSE
                  - action: CREATE
                    resourceType: UNIVERSE
        description: create role form data
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
              examples:
                CreateRole200Example:
                  summary: Default createRole 200 response
                  x-microcks-default: true
                  value:
                    customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    permissionDetails:
                      permissionList:
                      - action: CREATE
                        resourceType: UNIVERSE
                      - action: CREATE
                        resourceType: UNIVERSE
                    name: name
                    description: description
                    updatedOn: 2022-12-12 13:07:18+00:00
                    roleType: System
                    createdOn: 2022-12-12 13:07:18+00:00
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Create a Custom Role
      tags:
      - RBAC management
      x-codegen-request-body-name: RoleFormData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/rbac/role/{rUUID}:
    delete:
      description: 'WARNING: This is a preview API that could change.'
      operationId: deleteRole
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: rUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YBPSuccess'
              examples:
                DeleteRole200Example:
                  summary: Default deleteRole 200 response
                  x-microcks-default: true
                  value:
                    success: true
                    message: message
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Delete a Custom Role
      tags:
      - RBAC management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    get:
      description: 'WARNING: This is a preview API that could change.'
      operationId: getRole
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: rUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
              examples:
                GetRole200Example:
                  summary: Default getRole 200 response
                  x-microcks-default: true
                  value:
                    customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    permissionDetails:
                      permissionList:
                      - action: CREATE
                        resourceType: UNIVERSE
                      - action: CREATE
                        resourceType: UNIVERSE
                    name: name
                    description: description
                    updatedOn: 2022-12-12 13:07:18+00:00
                    roleType: System
                    createdOn: 2022-12-12 13:07:18+00:00
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Get a Role's Information
      tags:
      - RBAC management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      description: 'WARNING: This is a preview API that could change.'
      operationId: editRole
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: rUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleFormData'
            examples:
              EditRoleRequestExample:
                summary: Default editRole request
                x-microcks-default: true
                value:
                  name: name
                  description: description
                  permissionList:
                  - action: CREATE
                    resourceType: UNIVERSE
                  - action: CREATE
                    resourceType: UNIVERSE
        description: edit role form data
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
              examples:
                EditRole200Example:
                  summary: Default editRole 200 response
                  x-microcks-default: true
                  value:
                    customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    permissionDetails:
                      permissionList:
                      - action: CREATE
                        resourceType: UNIVERSE
                      - action: CREATE
                        resourceType: UNIVERSE
                    name: name
                    description: description
                    updatedOn: 2022-12-12 13:07:18+00:00
                    roleType: System
                    createdOn: 2022-12-12 13:07:18+00:00
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Edit a Custom Role
      tags:
      - RBAC management
      x-codegen-request-body-name: RoleFormData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/rbac/role_binding:
    get:
      description: 'WARNING: This is a preview API that could change.'
      operationId: getRoleBindings
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - description: Optional user UUID to filter role binding map
        in: query
        name: userUUID
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties:
                  $ref: '#/components/schemas/RoleBinding'
                type: object
              examples:
                GetRoleBindings200Example:
                  summary: Default getRoleBindings 200 response
                  x-microcks-default: true
                  value: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Get All the Role Bindings Available
      tags:
      - RBAC management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/rbac/role_binding/{userUUID}:
    post:
      description: 'WARNING: This is a preview API that could change.'
      operationId: setRoleBinding
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: userUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleBindingFormData'
            examples:
              SetRoleBindingRequestExample:
                summary: Default setRoleBinding request
                x-microcks-default: true
                value:
                  roleResourceDefinitions:
                  - resourceGroup:
                      resourceDefinitionSet:
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                  - resourceGroup:
                      resourceDefinitionSet:
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                    roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        description: set role bindings form data
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/RoleBinding'
                type: array
              examples:
                SetRoleBinding200Example:
                  summary: Default setRoleBinding 200 response
                  x-microcks-default: true
                  value:
                  - principal:
                      groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      userUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      type: USER
                      uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    resourceGroup:
                      resourceDefinitionSet:
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                      - allowAll: true
                        resourceUUIDSet:
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                        resourceType: UNIVERSE
                    role:
                      customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      permissionDetails:
                        permissionList:
                        - action: CREATE
                          resourceType: UNIVERSE
                        - action: CREATE
                          resourceType: UNIVERSE
                      name: name
                      description: description
                      updatedOn: 2022-12-12 13:07:18+00:00
                      roleType: System
                      createdOn: 2022-12-12 13:07:18+00:00
                      roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    createTime: 2022-12-12 13:07:18+00:00
                    updateTime: 2022-12-12 13:07:18+00:00
                    groupInfo:
                      groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      identifier: identifier
                      customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      creationDate: 2022-12-12 13:07:18+00:00
                      type: LDAP
                      roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    type: System
                    user:
                      ldapSpecifiedRole: true
                      customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      role: Admin
                      authTokenIssueDate: 2021-06-17 15:00:05+00:00
                      timezone: timezone
                      oidcJwtAuthToken: oidcJwtAuthToken
                      groupMemberships:
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      userType: local
                      creationDate: 2022-12-12 13:07:18+00:00
                      uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      email: username1@example.com
                      primary: true
                    uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Set the Role Bindings of a User
      tags:
      - RBAC management
      x-codegen-request-body-name: RoleBindingFormData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    Permission:
      example:
        action: CREATE
        resourceType: UNIVERSE
      properties:
        action:
          enum:
          - CREATE
          - READ
          - UPDATE
          - DELETE
          - PAUSE_RESUME
          - BACKUP_RESTORE
          - UPDATE_ROLE_BINDINGS
          - UPDATE_PROFILE
          - SUPER_ADMIN_ACTIONS
          - XCLUSTER
          - DEBUG
          - TROUBLESHOOT
          type: string
          example: CREATE
        resourceType:
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
          example: UNIVERSE
      type: object
    GroupMappingInfo:
      example:
        groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        identifier: identifier
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        creationDate: 2022-12-12 13:07:18+00:00
        type: LDAP
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        creationDate:
          description: Group mapping creation time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        customerUUID:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        groupUUID:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        identifier:
          type: string
          example: example-identifier
        roleUUID:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type:
          enum:
          - LDAP
          - OIDC
          type: string
          example: LDAP
      required:
      - customerUUID
      - groupUUID
      - identifier
      - roleUUID
      - type
      type: object
    Principal:
      example:
        groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        userUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: USER
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        groupUUID:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type:
          enum:
          - USER
          - LDAP_GROUP
          - OIDC_GROUP
          type: string
          example: USER
        userUUID:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        uuid:
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - groupUUID
      - type
      - userUUID
      - uuid
      type: object
    Role:
      example:
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        permissionDetails:
          permissionList:
          - action: CREATE
            resourceType: UNIVERSE
          - action: CREATE
            resourceType: UNIVERSE
        name: name
        description: description
        updatedOn: 2022-12-12 13:07:18+00:00
        roleType: System
        createdOn: 2022-12-12 13:07:18+00:00
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        createdOn:
          description: Role create time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        customerUUID:
          description: Customer UUID
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        description:
          description: Role description
          type: string
          example: Example description
        name:
          description: Role name
          type: string
          example: example-name
        permissionDetails:
          $ref: '#/components/schemas/PermissionDetails'
        roleType:
          description: Type of the role
          enum:
          - System
          - Custom
          type: string
          example: System
        roleUUID:
          description: Role UUID
          format: uuid
          readOnly: true
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        updatedOn:
          description: Role last updated time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
      type: object
    PermissionDetails:
      example:
        permissionList:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
      properties:
        permissionList:
          description: Set of permissions
          items:
            $ref: '#/components/schemas/Permission'
          type: array
          uniqueItems: true
          example:
          - action: CREATE
            resourceType: UNIVERSE
      type: object
    PermissionInfo:
      example:
        permissionValidOnResource: true
        prerequisitePermissions:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
        name: name
        action: CREATE
        description: description
        resourceType: UNIVERSE
      properties:
        action:
          enum:
          - CREATE
          - READ
          - UPDATE
          - DELETE
          - PAUSE_RESUME
          - BACKUP_RESTORE
          - UPDATE_ROLE_BINDINGS
          - UPDATE_PROFILE
          - SUPER_ADMIN_ACTIONS
          - XCLUSTER
          - DEBUG
          - TROUBLESHOOT
          type: string
          example: CREATE
        description:
          type: string
          example: Example description
        name:
          type: string
          example: example-name
        permissionValidOnResource:
          type: boolean
          example: true
        prerequisitePermissions:
          items:
            $ref: '#/components/schemas/Permission'
          type: array
          uniqueItems: true
          example:
          - action: CREATE
            resourceType: UNIVERSE
        resourceType:
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
          example: UNIVERSE
      type: object
    RoleBindingFormData:
      description: Role Binding form metadata
      example:
        roleResourceDefinitions:
        - resourceGroup:
            resourceDefinitionSet:
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - resourceGroup:
            resourceDefinitionSet:
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        roleResourceDefinitions:
          description: List of roles and resource groups defined.
          items:
            $ref: '#/components/schemas/RoleResourceDefinition'
          type: array
          example:
          - resourceGroup:
              resourceDefinitionSet:
              - allowAll: true
                resourceUUIDSet:
                - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                resourceType: UNIVERSE
              - allowAll: true
                resourceUUIDSet:
                - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                resourceType: UNIVERSE
            roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - roleResourceDefinitions
      type: object
    RoleFormData:
      description: Role form metadata
      example:
        name: name
        description: description
        permissionList:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
      properties:
        description:
          description: Description of the role to be created
          type: string
          example: Example description
        name:
          description: Name of the role to be created
          type: string
          example: example-name
        permissionList:
          description: List of permissions given to the role
          items:
            $ref: '#/components/schemas/Permission'
          type: array
          uniqueItems: true
          example:
          - action: CREATE
            resourceType: UNIVERSE
      required:
      - description
      - name
      - permissionList
      type: object
    YBPSuccess:
      example:
        success: true
        message: message
      properties:
        message:
          description: API response message.
          readOnly: true
          type: string
          example: Example message
        success:
          description: API operation status. A value of true indicates the operation was successful.
          readOnly: true
          type: boolean
          example: true
      type: object
    ResourceGroup:
      example:
        resourceDefinitionSet:
        - allowAll: true
          resourceUUIDSet:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          resourceType: UNIVERSE
        - allowAll: true
          resourceUUIDSet:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          resourceType: UNIVERSE
      properties:
        resourceDefinitionSet:
          items:
            $ref: '#/components/schemas/ResourceDefinition'
          type: array
          uniqueItems: true
          example:
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
      required:
      - resourceDefinitionSet
      type: object
    RoleResourceDefinition:
      description: Defines the association of Role to Resource Groups.
      example:
        resourceGroup:
          resourceDefinitionSet:
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        resourceGroup:
          $ref: '#/components/schemas/ResourceGroup'
        roleUUID:
          description: UUID of the role to attach resource group to.
          format: uuid
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - roleUUID
      type: object
    ResourceDefinition:
      example:
        allowAll: true
        resourceUUIDSet:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        resourceType: UNIVERSE
      properties:
        allowAll:
          description: Select all resources (including future resources)
          type: boolean
          example: true
        resourceType:
          description: Resource Type
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
          example: UNIVERSE
        resourceUUIDSet:
          description: Set of resource uuids
          items:
            format: uuid
            type: string
          type: array
          uniqueItems: true
          example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      type: object
    RoleBinding:
      example:
        principal:
          groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: USER
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        resourceGroup:
          resourceDefinitionSet:
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
        role:
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissionDetails:
            permissionList:
            - action: CREATE
              resourceType: UNIVERSE
            - action: CREATE
              resourceType: UNIVERSE
          name: name
          description: description
          updatedOn: 2022-12-12 13:07:18+00:00
          roleType: System
          createdOn: 2022-12-12 13:07:18+00:00
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        createTime: 2022-12-12 13:07:18+00:00
        updateTime: 2022-12-12 13:07:18+00:00
        groupInfo:
          groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          identifier: identifier
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          creationDate: 2022-12-12 13:07:18+00:00
          type: LDAP
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: System
        user:
          ldapSpecifiedRole: true
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          role: Admin
          authTokenIssueDate: 2021-06-17 15:00:05+00:00
          timezone: timezone
          oidcJwtAuthToken: oidcJwtAuthToken
          groupMemberships:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userType: local
          creationDate: 2022-12-12 13:07:18+00:00
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          email: username1@example.com
          primary: true
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        createTime:
          description: RoleBinding create time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        groupInfo:
          $ref: '#/components/schemas/GroupMappingInfo'
        principal:
          $ref: '#/components/schemas/Principal'
        resourceGroup:
          $ref: '#/components/schemas/ResourceGroup'
        role:
          $ref: '#/components/schemas/Role'
        type:
          description: Role binding type
          enum:
          - System
          - Custom
          type: string
          example: System
        updateTime:
          description: RoleBinding last updated time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        user:
          $ref: '#/components/schemas/Users'
        uuid:
          description: UUID
          format: uuid
          readOnly: true
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - principal
      type: object
    Users:
      description: A user associated with a customer
      example:
        ldapSpecifiedRole: true
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        role: Admin
        authTokenIssueDate: 2021-06-17 15:00:05+00:00
        timezone: timezone
        oidcJwtAuthToken: oidcJwtAuthToken
        groupMemberships:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        userType: local
        creationDate: 2022-12-12 13:07:18+00:00
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        email: username1@example.com
        primary: true
      properties:
        authTokenIssueDate:
          description: UI session token creation date
          example: 2021-06-17 15:00:05+00:00
          format: date-time
          readOnly: true
          type: string
        creationDate:
          description: User creation date
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          readOnly: true
          type: string
        customerUUID:
          description: Customer UUID
          format: uuid
          readOnly: true
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        email:
          description: User email address
          example: username1@example.com
          type: string
        groupMemberships:
          items:
            format: uuid
            type: string
          type: array
          uniqueItems: true
          example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        ldapSpecifiedRole:
          description: LDAP Specified Role
          type: boolean
          example: true
        oidcJwtAuthToken:
          readOnly: true
          type: string
          example: REDACTED
        primary:
          type: boolean
          example: true
        role:
          description: <b style="color:#ff0000">Deprecated since YBA version 2.19.3.0.</b> Use  getRoleBindings instead.
          enum:
          - ConnectOnly
          - ReadOnly
          - BackupAdmin
          - Admin
          - SuperAdmin
          example: Admin
          type: string
        timezone:
          description: User timezone
          type: string
          example: us-east-1a
        userType:
          description: User Type
          enum:
          - local
          - ldap
          - oidc
          type: string
          example: local
        uuid:
          description: User UUID
          format: uuid
          readOnly: true
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - email
      - groupMemberships
      - primary
      type: object
    Permission_2:
      example:
        action: CREATE
        resourceType: UNIVERSE
      properties:
        action:
          enum:
          - CREATE
          - READ
          - UPDATE
          - DELETE
          - PAUSE_RESUME
          - BACKUP_RESTORE
          - UPDATE_ROLE_BINDINGS
          - UPDATE_PROFILE
          - SUPER_ADMIN_ACTIONS
          - XCLUSTER
          - DEBUG
          - TROUBLESHOOT
          type: string
        resourceType:
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
      type: object
    GroupMappingInfo_2:
      example:
        groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        identifier: identifier
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        creationDate: 2022-12-12 13:07:18+00:00
        type: LDAP
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        creationDate:
          description: Group mapping creation time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        customerUUID:
          format: uuid
          type: string
        groupUUID:
          format: uuid
          type: string
        identifier:
          type: string
        roleUUID:
          format: uuid
          type: string
        type:
          enum:
          - LDAP
          - OIDC
          type: string
      required:
      - customerUUID
      - groupUUID
      - identifier
      - roleUUID
      - type
      type: object
    Principal_2:
      example:
        groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        userUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: USER
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        groupUUID:
          format: uuid
          type: string
        type:
          enum:
          - USER
          - LDAP_GROUP
          - OIDC_GROUP
          type: string
        userUUID:
          format: uuid
          type: string
        uuid:
          format: uuid
          type: string
      required:
      - groupUUID
      - type
      - userUUID
      - uuid
      type: object
    Role_2:
      example:
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        permissionDetails:
          permissionList:
          - action: CREATE
            resourceType: UNIVERSE
          - action: CREATE
            resourceType: UNIVERSE
        name: name
        description: description
        updatedOn: 2022-12-12 13:07:18+00:00
        roleType: System
        createdOn: 2022-12-12 13:07:18+00:00
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        createdOn:
          description: Role create time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        customerUUID:
          description: Customer UUID
          format: uuid
          type: string
        description:
          description: Role description
          type: string
        name:
          description: Role name
          type: string
        permissionDetails:
          $ref: '#/components/schemas/PermissionDetails_2'
        roleType:
          description: Type of the role
          enum:
          - System
          - Custom
          type: string
        roleUUID:
          description: Role UUID
          format: uuid
          readOnly: true
          type: string
        updatedOn:
          description: Role last updated time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
      type: object
    PermissionDetails_2:
      example:
        permissionList:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
      properties:
        permissionList:
          description: Set of permissions
          items:
            $ref: '#/components/schemas/Permission_2'
          type: array
          uniqueItems: true
      type: object
    PermissionInfo_2:
      example:
        permissionValidOnResource: true
        prerequisitePermissions:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
        name: name
        action: CREATE
        description: description
        resourceType: UNIVERSE
      properties:
        action:
          enum:
          - CREATE
          - READ
          - UPDATE
          - DELETE
          - PAUSE_RESUME
          - BACKUP_RESTORE
          - UPDATE_ROLE_BINDINGS
          - UPDATE_PROFILE
          - SUPER_ADMIN_ACTIONS
          - XCLUSTER
          - DEBUG
          - TROUBLESHOOT
          type: string
        description:
          type: string
        name:
          type: string
        permissionValidOnResource:
          type: boolean
        prerequisitePermissions:
          items:
            $ref: '#/components/schemas/Permission_2'
          type: array
          uniqueItems: true
        resourceType:
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
      type: object
    RoleBindingFormData_2:
      description: Role Binding form metadata
      example:
        roleResourceDefinitions:
        - resourceGroup:
            resourceDefinitionSet:
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - resourceGroup:
            resourceDefinitionSet:
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
            - allowAll: true
              resourceUUIDSet:
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              resourceType: UNIVERSE
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        roleResourceDefinitions:
          description: List of roles and resource groups defined.
          items:
            $ref: '#/components/schemas/RoleResourceDefinition_2'
          type: array
      required:
      - roleResourceDefinitions
      type: object
    RoleFormData_2:
      description: Role form metadata
      example:
        name: name
        description: description
        permissionList:
        - action: CREATE
          resourceType: UNIVERSE
        - action: CREATE
          resourceType: UNIVERSE
      properties:
        description:
          description: Description of the role to be created
          type: string
        name:
          description: Name of the role to be created
          type: string
        permissionList:
          description: List of permissions given to the role
          items:
            $ref: '#/components/schemas/Permission_2'
          type: array
          uniqueItems: true
      required:
      - description
      - name
      - permissionList
      type: object
    YBPSuccess_2:
      example:
        success: true
        message: message
      properties:
        message:
          description: API response message.
          readOnly: true
          type: string
        success:
          description: API operation status. A value of true indicates the operation was successful.
          readOnly: true
          type: boolean
      type: object
    ResourceGroup_2:
      example:
        resourceDefinitionSet:
        - allowAll: true
          resourceUUIDSet:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          resourceType: UNIVERSE
        - allowAll: true
          resourceUUIDSet:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          resourceType: UNIVERSE
      properties:
        resourceDefinitionSet:
          items:
            $ref: '#/components/schemas/ResourceDefinition_2'
          type: array
          uniqueItems: true
      required:
      - resourceDefinitionSet
      type: object
    RoleResourceDefinition_2:
      description: Defines the association of Role to Resource Groups.
      example:
        resourceGroup:
          resourceDefinitionSet:
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
        roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        resourceGroup:
          $ref: '#/components/schemas/ResourceGroup_2'
        roleUUID:
          description: UUID of the role to attach resource group to.
          format: uuid
          type: string
      required:
      - roleUUID
      type: object
    ResourceDefinition_2:
      example:
        allowAll: true
        resourceUUIDSet:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        resourceType: UNIVERSE
      properties:
        allowAll:
          description: Select all resources (including future resources)
          type: boolean
        resourceType:
          description: Resource Type
          enum:
          - UNIVERSE
          - ROLE
          - USER
          - OTHER
          type: string
        resourceUUIDSet:
          description: Set of resource uuids
          items:
            format: uuid
            type: string
          type: array
          uniqueItems: true
      type: object
    RoleBinding_2:
      example:
        principal:
          groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: USER
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        resourceGroup:
          resourceDefinitionSet:
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
          - allowAll: true
            resourceUUIDSet:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            resourceType: UNIVERSE
        role:
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissionDetails:
            permissionList:
            - action: CREATE
              resourceType: UNIVERSE
            - action: CREATE
              resourceType: UNIVERSE
          name: name
          description: description
          updatedOn: 2022-12-12 13:07:18+00:00
          roleType: System
          createdOn: 2022-12-12 13:07:18+00:00
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        createTime: 2022-12-12 13:07:18+00:00
        updateTime: 2022-12-12 13:07:18+00:00
        groupInfo:
          groupUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          identifier: identifier
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          creationDate: 2022-12-12 13:07:18+00:00
          type: LDAP
          roleUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: System
        user:
          ldapSpecifiedRole: true
          customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          role: Admin
          authTokenIssueDate: 2021-06-17 15:00:05+00:00
          timezone: timezone
          oidcJwtAuthToken: oidcJwtAuthToken
          groupMemberships:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userType: local
          creationDate: 2022-12-12 13:07:18+00:00
          uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          email: username1@example.com
          primary: true
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        createTime:
          description: RoleBinding create time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        groupInfo:
          $ref: '#/components/schemas/GroupMappingInfo_2'
        principal:
          $ref: '#/components/schemas/Principal_2'
        resourceGroup:
          $ref: '#/components/schemas/ResourceGroup_2'
        role:
          $ref: '#/components/schemas/Role_2'
        type:
          description: Role binding type
          enum:
          - System
          - Custom
          type: string
        updateTime:
          description: RoleBinding last updated time
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          type: string
        user:
          $ref: '#/components/schemas/Users_2'
        uuid:
          description: UUID
          format: uuid
          readOnly: true
          type: string
      required:
      - principal
      type: object
    Users_2:
      description: A user associated with a customer
      example:
        ldapSpecifiedRole: true
        customerUUID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        role: Admin
        authTokenIssueDate: 2021-06-17 15:00:05+00:00
        timezone: timezone
        oidcJwtAuthToken: oidcJwtAuthToken
        groupMemberships:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        userType: local
        creationDate: 2022-12-12 13:07:18+00:00
        uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        email: username1@example.com
        primary: true
      properties:
        authTokenIssueDate:
          description: UI session token creation date
          example: 2021-06-17 15:00:05+00:00
          format: date-time
          readOnly: true
          type: string
        creationDate:
          description: User creation date
          example: 2022-12-12 13:07:18+00:00
          format: date-time
          readOnly: true
          type: string
        customerUUID:
          description: Customer UUID
          format: uuid
          readOnly: true
          type: string
        email:
          description: User email address
          example: username1@example.com
          type: string
        groupMemberships:
          items:
            format: uuid
            type: string
          type: array
          uniqueItems: true
        ldapSpecifiedRole:
          description: LDAP Specified Role
          type: boolean
        oidcJwtAuthToken:
          readOnly: true
          type: string
        primary:
          type: boolean
        role:
          description: <b style="color:#ff0000">Deprecated since YBA version 2.19.3.0.</b> Use  getRoleBindings instead.
          enum:
          - ConnectOnly
          - ReadOnly
          - BackupAdmin
          - Admin
          - SuperAdmin
          example: Admin
          type: string
        timezone:
          description: User timezone
          type: string
        userType:
          description: User Type
          enum:
          - local
          - ldap
          - oidc
          type: string
        uuid:
          description: User UUID
          format: uuid
          readOnly: true
          type: string
      required:
      - email
      - groupMemberships
      - primary
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API key obtained from the YugabyteDB Aeon UI under User Profile > API Keys. Pass the key as a Bearer token in the Authorization header.
externalDocs:
  description: YugabyteDB Aeon REST API Documentation
  url: https://docs.yugabyte.com/stable/yugabyte-cloud/managed-automation/managed-api/
