openapi: 3.1.0
info:
  title: YugabyteDB Aeon REST Access Keys LDAPOIDC Role management API
  description: The YugabyteDB Aeon REST API provides programmatic access to YugabyteDB's fully managed cloud database service. Developers and operators can use it to deploy and manage database clusters, configure read replicas, schedule and execute on-demand backups and restores, manage IP allow lists, and set up monitoring and alerts. Authentication is performed using API keys passed as bearer tokens in the Authorization header. All paths are scoped to an account and project, which can be obtained from the YugabyteDB Aeon UI profile page.
  version: v1
  contact:
    name: Yugabyte Support
    url: https://support.yugabyte.com
  termsOfService: https://www.yugabyte.com/yugabytedb-managed-service-terms/
  x-generated-from: documentation
  x-source-url: https://api-docs.yugabyte.com/docs/managed-apis/
  x-last-validated: '2026-05-03'
servers:
- url: https://cloud.yugabyte.com/api/public/v1
  description: YugabyteDB Aeon Production Server
security:
- bearerAuth: []
tags:
- name: LDAPOIDC Role management
paths:
  /api/v1/customers/{cUUID}/ldap_mappings:
    get:
      deprecated: true
      description: <b style="color:#ff0000">Deprecated since YBA version 2024.2.0.0.</b> Please use the v2 /auth/group-mappings GET endpoint instead. Note that this API will not return the custom roles assigned to groups via the new /api/v2/customers/{cUUID}/auth/group-mappings API.
      operationId: listLdapDnToYbaRoles
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LdapDnToYbaRoleData'
              examples:
                ListLdapDnToYbaRoles200Example:
                  summary: Default listLdapDnToYbaRoles 200 response
                  x-microcks-default: true
                  value:
                    ldapDnToYbaRolePairs:
                    - ybaRole: ConnectOnly
                      distinguishedName: distinguishedName
                    - ybaRole: ConnectOnly
                      distinguishedName: distinguishedName
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List LDAP Mappings
      tags:
      - LDAPOIDC Role management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      deprecated: true
      description: <b style="color:#ff0000">Deprecated since YBA version 2024.2.0.0.</b> Please use the v2 /auth/group-mappings PUT endpoint instead
      operationId: setLdapDnToYbaRoles
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LdapDnToYbaRoleData'
            examples:
              SetLdapDnToYbaRolesRequestExample:
                summary: Default setLdapDnToYbaRoles request
                x-microcks-default: true
                value:
                  ldapDnToYbaRolePairs:
                  - ybaRole: ConnectOnly
                    distinguishedName: distinguishedName
                  - ybaRole: ConnectOnly
                    distinguishedName: distinguishedName
        description: New LDAP Mappings to be set
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Set LDAP Mappings
      tags:
      - LDAPOIDC Role management
      x-codegen-request-body-name: ldapMappings
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/oidc_mappings:
    get:
      deprecated: true
      description: <b style="color:#ff0000">Deprecated since YBA version 2024.2.0.0.</b> Please use the v2 /auth/group-mappings GET endpoint instead. Note that this API will not return the custom roles assigned to groups via the new /api/v2/customers/{cUUID}/auth/group-mappings API.
      operationId: listOidcGroupToYbaRoles
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcGroupToYbaRolesData'
              examples:
                ListOidcGroupToYbaRoles200Example:
                  summary: Default listOidcGroupToYbaRoles 200 response
                  x-microcks-default: true
                  value:
                    oidcGroupToYbaRolesPairs:
                    - groupName: groupName
                      roles:
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    - groupName: groupName
                      roles:
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                      - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List OIDC Group Mappings
      tags:
      - LDAPOIDC Role management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      deprecated: true
      description: <b style="color:#ff0000">Deprecated since YBA version 2024.2.0.0.</b> Please use the v2 /auth/group-mappings PUT endpoint instead
      operationId: mapOidcGroupToYbaRoles
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: query
        name: request
        schema: {}
        example: example-request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcGroupToYbaRolesData'
            examples:
              MapOidcGroupToYbaRolesRequestExample:
                summary: Default mapOidcGroupToYbaRoles request
                x-microcks-default: true
                value:
                  oidcGroupToYbaRolesPairs:
                  - groupName: groupName
                    roles:
                    - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                  - groupName: groupName
                    roles:
                    - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                    - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        description: New OIDC Mappings to be set
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Set OIDC Mappings
      tags:
      - LDAPOIDC Role management
      x-codegen-request-body-name: oidcMappings
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/oidc_mappings/{groupName}:
    delete:
      deprecated: true
      description: <b style="color:#ff0000">Deprecated since YBA version 2024.2.0.0.</b> Please use the v2 /auth/group-mappings/{groupUUID} DELETE endpoint instead
      operationId: deleteOidcGroupMapping
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: groupName
        required: true
        schema:
          type: string
        example: example-groupName
      - in: query
        name: request
        schema: {}
        example: example-request
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YBPSuccess'
              examples:
                DeleteOidcGroupMapping200Example:
                  summary: Default deleteOidcGroupMapping 200 response
                  x-microcks-default: true
                  value:
                    success: true
                    message: message
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Delete a OIDC Group Mapping
      tags:
      - LDAPOIDC Role management
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    LdapDnYbaRoleDataPair:
      example:
        ybaRole: ConnectOnly
        distinguishedName: distinguishedName
      properties:
        distinguishedName:
          type: string
          example: example-distinguishedName
        ybaRole:
          enum:
          - ConnectOnly
          - ReadOnly
          - BackupAdmin
          - Admin
          - SuperAdmin
          type: string
          example: ConnectOnly
      required:
      - distinguishedName
      - ybaRole
      type: object
    LdapDnToYbaRoleData:
      description: A list of LDAP DN, YBA role pairs
      example:
        ldapDnToYbaRolePairs:
        - ybaRole: ConnectOnly
          distinguishedName: distinguishedName
        - ybaRole: ConnectOnly
          distinguishedName: distinguishedName
      properties:
        ldapDnToYbaRolePairs:
          description: ' list of pairs of distinguishedName and ybaRole'
          items:
            $ref: '#/components/schemas/LdapDnYbaRoleDataPair'
          type: array
          example:
          - ybaRole: ConnectOnly
            distinguishedName: distinguishedName
      type: object
    OidcGroupToYbaRolesData:
      example:
        oidcGroupToYbaRolesPairs:
        - groupName: groupName
          roles:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - groupName: groupName
          roles:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        oidcGroupToYbaRolesPairs:
          description: ' list of pairs of groupName and roles'
          items:
            $ref: '#/components/schemas/OidcGroupToYbaRolesPair'
          type: array
          example:
          - groupName: groupName
            roles:
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      type: object
    OidcGroupToYbaRolesPair:
      example:
        groupName: groupName
        roles:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        groupName:
          type: string
          example: example-groupName
        roles:
          items:
            format: uuid
            type: string
          type: array
          example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      required:
      - groupName
      - roles
      type: object
    YBPSuccess:
      example:
        success: true
        message: message
      properties:
        message:
          description: API response message.
          readOnly: true
          type: string
          example: Example message
        success:
          description: API operation status. A value of true indicates the operation was successful.
          readOnly: true
          type: boolean
          example: true
      type: object
    LdapDnYbaRoleDataPair_2:
      example:
        ybaRole: ConnectOnly
        distinguishedName: distinguishedName
      properties:
        distinguishedName:
          type: string
        ybaRole:
          enum:
          - ConnectOnly
          - ReadOnly
          - BackupAdmin
          - Admin
          - SuperAdmin
          type: string
      required:
      - distinguishedName
      - ybaRole
      type: object
    LdapDnToYbaRoleData_2:
      description: A list of LDAP DN, YBA role pairs
      example:
        ldapDnToYbaRolePairs:
        - ybaRole: ConnectOnly
          distinguishedName: distinguishedName
        - ybaRole: ConnectOnly
          distinguishedName: distinguishedName
      properties:
        ldapDnToYbaRolePairs:
          description: ' list of pairs of distinguishedName and ybaRole'
          items:
            $ref: '#/components/schemas/LdapDnYbaRoleDataPair_2'
          type: array
      type: object
    OidcGroupToYbaRolesData_2:
      example:
        oidcGroupToYbaRolesPairs:
        - groupName: groupName
          roles:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - groupName: groupName
          roles:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        oidcGroupToYbaRolesPairs:
          description: ' list of pairs of groupName and roles'
          items:
            $ref: '#/components/schemas/OidcGroupToYbaRolesPair_2'
          type: array
      type: object
    OidcGroupToYbaRolesPair_2:
      example:
        groupName: groupName
        roles:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        groupName:
          type: string
        roles:
          items:
            format: uuid
            type: string
          type: array
      required:
      - groupName
      - roles
      type: object
    YBPSuccess_2:
      example:
        success: true
        message: message
      properties:
        message:
          description: API response message.
          readOnly: true
          type: string
        success:
          description: API operation status. A value of true indicates the operation was successful.
          readOnly: true
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API key obtained from the YugabyteDB Aeon UI under User Profile > API Keys. Pass the key as a Bearer token in the Authorization header.
externalDocs:
  description: YugabyteDB Aeon REST API Documentation
  url: https://docs.yugabyte.com/stable/yugabyte-cloud/managed-automation/managed-api/
