openapi: 3.1.0
info:
  title: YugabyteDB Aeon REST Access Keys Universe node metadata (metamaster) API
  description: The YugabyteDB Aeon REST API provides programmatic access to YugabyteDB's fully managed cloud database service. Developers and operators can use it to deploy and manage database clusters, configure read replicas, schedule and execute on-demand backups and restores, manage IP allow lists, and set up monitoring and alerts. Authentication is performed using API keys passed as bearer tokens in the Authorization header. All paths are scoped to an account and project, which can be obtained from the YugabyteDB Aeon UI profile page.
  version: v1
  contact:
    name: Yugabyte Support
    url: https://support.yugabyte.com
  termsOfService: https://www.yugabyte.com/yugabytedb-managed-service-terms/
  x-generated-from: documentation
  x-source-url: https://api-docs.yugabyte.com/docs/managed-apis/
  x-last-validated: '2026-05-03'
servers:
- url: https://cloud.yugabyte.com/api/public/v1
  description: YugabyteDB Aeon Production Server
security:
- bearerAuth: []
tags:
- name: Universe node metadata (metamaster)
paths:
  /api/v1/customers/{cUUID}/universes/{uniUUID}/master_lb_state:
    get:
      description: YbaApi Internal. Available since YBA version 2024.2.0
      operationId: getMasterLBState
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: uniUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLBStateResponse'
              examples:
                GetMasterLBState200Example:
                  summary: Default getMasterLBState 200 response
                  x-microcks-default: true
                  value:
                    isEnabled: true
                    isIdle: true
                    estTimeToBalanceSecs: 0
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere Get the State of Master Load Balancing Ops
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/universes/{uniUUID}/masters:
    get:
      description: Available since YBA version 2.2.0.0.
      operationId: getMasterAddresses
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: uniUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
              examples:
                GetMasterAddresses200Example:
                  summary: Default getMasterAddresses 200 response
                  x-microcks-default: true
                  value: string
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List a Master Node's Addresses
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/universes/{uniUUID}/redisservers:
    get:
      description: Available since YBA version 2.2.0.0.
      operationId: getRedisServerAddresses
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: uniUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
              examples:
                GetRedisServerAddresses200Example:
                  summary: Default getRedisServerAddresses 200 response
                  x-microcks-default: true
                  value: string
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List a REDIS Server's Addresses
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/universes/{uniUUID}/yqlservers:
    get:
      description: Available since YBA version 2.2.0.0.
      operationId: getYQLServerAddresses
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: uniUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
              examples:
                GetYQLServerAddresses200Example:
                  summary: Default getYQLServerAddresses 200 response
                  x-microcks-default: true
                  value: string
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List a YQL Server's Addresses
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1/customers/{cUUID}/universes/{uniUUID}/ysqlservers:
    get:
      description: Available since YBA version 2.2.0.0.
      operationId: getYSQLServerAddresses
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      - in: path
        name: uniUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
              examples:
                GetYSQLServerAddresses200Example:
                  summary: Default getYSQLServerAddresses 200 response
                  x-microcks-default: true
                  value: string
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List a YSQL Server's Addresses
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /metamaster/universe/{universeUUID}:
    get:
      operationId: getUniverseMasterNodes
      parameters:
      - in: path
        name: universeUUID
        required: true
        schema:
          format: uuid
          type: string
        example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MastersList'
              examples:
                GetUniverseMasterNodes200Example:
                  summary: Default getUniverseMasterNodes 200 response
                  x-microcks-default: true
                  value:
                    masters:
                    - cloudInfo:
                        mount_roots: mount_roots
                        kubernetesNamespace: kubernetesNamespace
                        public_ip: public_ip
                        secondary_subnet_id: secondary_subnet_id
                        private_dns: private_dns
                        useTimeSync: true
                        kubernetesPodName: kubernetesPodName
                        root_volume: root_volume
                        secondary_private_ip: secondary_private_ip
                        private_ip: private_ip
                        cloud: cloud
                        lun_indexes:
                        - 6
                        - 6
                        assignPublicIP: true
                        az: az
                        subnet_id: subnet_id
                        public_dns: public_dns
                        region: region
                        instance_type: instance_type
                      masterRpcPort: 0
                    - cloudInfo:
                        mount_roots: mount_roots
                        kubernetesNamespace: kubernetesNamespace
                        public_ip: public_ip
                        secondary_subnet_id: secondary_subnet_id
                        private_dns: private_dns
                        useTimeSync: true
                        kubernetesPodName: kubernetesPodName
                        root_volume: root_volume
                        secondary_private_ip: secondary_private_ip
                        private_ip: private_ip
                        cloud: cloud
                        lun_indexes:
                        - 6
                        - 6
                        assignPublicIP: true
                        az: az
                        subnet_id: subnet_id
                        public_dns: public_dns
                        region: region
                        instance_type: instance_type
                      masterRpcPort: 0
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: YugabyteDB Anywhere List a Universe's Master Nodes
      tags:
      - Universe node metadata (metamaster)
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    MasterNode:
      example:
        cloudInfo:
          mount_roots: mount_roots
          kubernetesNamespace: kubernetesNamespace
          public_ip: public_ip
          secondary_subnet_id: secondary_subnet_id
          private_dns: private_dns
          useTimeSync: true
          kubernetesPodName: kubernetesPodName
          root_volume: root_volume
          secondary_private_ip: secondary_private_ip
          private_ip: private_ip
          cloud: cloud
          lun_indexes:
          - 6
          - 6
          assignPublicIP: true
          az: az
          subnet_id: subnet_id
          public_dns: public_dns
          region: region
          instance_type: instance_type
        masterRpcPort: 0
      properties:
        cloudInfo:
          $ref: '#/components/schemas/CloudSpecificInfo'
        masterRpcPort:
          format: int32
          type: integer
          example: 5433
      required:
      - cloudInfo
      - masterRpcPort
      type: object
    MastersList:
      example:
        masters:
        - cloudInfo:
            mount_roots: mount_roots
            kubernetesNamespace: kubernetesNamespace
            public_ip: public_ip
            secondary_subnet_id: secondary_subnet_id
            private_dns: private_dns
            useTimeSync: true
            kubernetesPodName: kubernetesPodName
            root_volume: root_volume
            secondary_private_ip: secondary_private_ip
            private_ip: private_ip
            cloud: cloud
            lun_indexes:
            - 6
            - 6
            assignPublicIP: true
            az: az
            subnet_id: subnet_id
            public_dns: public_dns
            region: region
            instance_type: instance_type
          masterRpcPort: 0
        - cloudInfo:
            mount_roots: mount_roots
            kubernetesNamespace: kubernetesNamespace
            public_ip: public_ip
            secondary_subnet_id: secondary_subnet_id
            private_dns: private_dns
            useTimeSync: true
            kubernetesPodName: kubernetesPodName
            root_volume: root_volume
            secondary_private_ip: secondary_private_ip
            private_ip: private_ip
            cloud: cloud
            lun_indexes:
            - 6
            - 6
            assignPublicIP: true
            az: az
            subnet_id: subnet_id
            public_dns: public_dns
            region: region
            instance_type: instance_type
          masterRpcPort: 0
      properties:
        masters:
          items:
            $ref: '#/components/schemas/MasterNode'
          type: array
          example:
          - cloudInfo:
              mount_roots: mount_roots
              kubernetesNamespace: kubernetesNamespace
              public_ip: public_ip
              secondary_subnet_id: secondary_subnet_id
              private_dns: private_dns
              useTimeSync: true
              kubernetesPodName: kubernetesPodName
              root_volume: root_volume
              secondary_private_ip: secondary_private_ip
              private_ip: private_ip
              cloud: cloud
              lun_indexes:
              - 6
              - 6
              assignPublicIP: true
              az: az
              subnet_id: subnet_id
              public_dns: public_dns
              region: region
              instance_type: instance_type
            masterRpcPort: 0
      required:
      - masters
      type: object
    MasterLBStateResponse:
      description: Master tablet load balancer status
      example:
        isEnabled: true
        isIdle: true
        estTimeToBalanceSecs: 0
      properties:
        estTimeToBalanceSecs:
          description: YbaApi Internal Estimate of time for which master tablet load balancer will be active
          format: int64
          type: integer
          example: 1000
        isEnabled:
          description: YbaApi Internal Whether master tablet load balancer is enabled
          type: boolean
          example: true
        isIdle:
          description: YbaApi Internal Whether master tablet load balancer is inactive
          type: boolean
          example: true
      required:
      - isEnabled
      type: object
    CloudSpecificInfo:
      description: Node information reported by the cloud provider
      example:
        mount_roots: mount_roots
        kubernetesNamespace: kubernetesNamespace
        public_ip: public_ip
        secondary_subnet_id: secondary_subnet_id
        private_dns: private_dns
        useTimeSync: true
        kubernetesPodName: kubernetesPodName
        root_volume: root_volume
        secondary_private_ip: secondary_private_ip
        private_ip: private_ip
        cloud: cloud
        lun_indexes:
        - 6
        - 6
        assignPublicIP: true
        az: az
        subnet_id: subnet_id
        public_dns: public_dns
        region: region
        instance_type: instance_type
      properties:
        assignPublicIP:
          description: True if the node has a public IP address assigned
          type: boolean
          example: true
        az:
          description: The node's availability zone
          type: string
          example: example-az
        cloud:
          description: The node's cloud provider
          type: string
          example: example-cloud
        instance_type:
          description: The node's instance type
          type: string
          example: DEFAULT
        kubernetesNamespace:
          description: Kubernetes namespace
          type: string
          example: example-kubernetesNamespace
        kubernetesPodName:
          description: Pod name in Kubernetes
          type: string
          example: example-kubernetesPodName
        lun_indexes:
          description: Mounted disks LUN indexes
          items:
            format: int32
            type: integer
          type: array
          example:
          - 100
        mount_roots:
          description: Mount roots
          type: string
          example: example-mount_roots
        private_dns:
          description: The node's private DNS
          type: string
          example: example-private_dns
        private_ip:
          description: The node's private IP address
          type: string
          example: 10.0.0.1
        public_dns:
          description: The node's public DNS name
          type: string
          example: example-public_dns
        public_ip:
          description: The node's public IP address
          type: string
          example: 10.0.0.1
        region:
          description: The node's region
          type: string
          example: us-east-1
        root_volume:
          description: Root volume ID or name
          type: string
          example: example-root_volume
        secondary_private_ip:
          description: Secondary Private IP
          type: string
          example: 10.0.0.1
        secondary_subnet_id:
          description: Secondary Subnet IP
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        subnet_id:
          description: ID of the subnet on which this node is deployed
          type: string
          example: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        useTimeSync:
          description: True if `use time sync` is enabled
          type: boolean
          example: true
      type: object
    MasterNode_2:
      example:
        cloudInfo:
          mount_roots: mount_roots
          kubernetesNamespace: kubernetesNamespace
          public_ip: public_ip
          secondary_subnet_id: secondary_subnet_id
          private_dns: private_dns
          useTimeSync: true
          kubernetesPodName: kubernetesPodName
          root_volume: root_volume
          secondary_private_ip: secondary_private_ip
          private_ip: private_ip
          cloud: cloud
          lun_indexes:
          - 6
          - 6
          assignPublicIP: true
          az: az
          subnet_id: subnet_id
          public_dns: public_dns
          region: region
          instance_type: instance_type
        masterRpcPort: 0
      properties:
        cloudInfo:
          $ref: '#/components/schemas/CloudSpecificInfo_2'
        masterRpcPort:
          format: int32
          type: integer
      required:
      - cloudInfo
      - masterRpcPort
      type: object
    MastersList_2:
      example:
        masters:
        - cloudInfo:
            mount_roots: mount_roots
            kubernetesNamespace: kubernetesNamespace
            public_ip: public_ip
            secondary_subnet_id: secondary_subnet_id
            private_dns: private_dns
            useTimeSync: true
            kubernetesPodName: kubernetesPodName
            root_volume: root_volume
            secondary_private_ip: secondary_private_ip
            private_ip: private_ip
            cloud: cloud
            lun_indexes:
            - 6
            - 6
            assignPublicIP: true
            az: az
            subnet_id: subnet_id
            public_dns: public_dns
            region: region
            instance_type: instance_type
          masterRpcPort: 0
        - cloudInfo:
            mount_roots: mount_roots
            kubernetesNamespace: kubernetesNamespace
            public_ip: public_ip
            secondary_subnet_id: secondary_subnet_id
            private_dns: private_dns
            useTimeSync: true
            kubernetesPodName: kubernetesPodName
            root_volume: root_volume
            secondary_private_ip: secondary_private_ip
            private_ip: private_ip
            cloud: cloud
            lun_indexes:
            - 6
            - 6
            assignPublicIP: true
            az: az
            subnet_id: subnet_id
            public_dns: public_dns
            region: region
            instance_type: instance_type
          masterRpcPort: 0
      properties:
        masters:
          items:
            $ref: '#/components/schemas/MasterNode_2'
          type: array
      required:
      - masters
      type: object
    MasterLBStateResponse_2:
      description: Master tablet load balancer status
      example:
        isEnabled: true
        isIdle: true
        estTimeToBalanceSecs: 0
      properties:
        estTimeToBalanceSecs:
          description: YbaApi Internal Estimate of time for which master tablet load balancer will be active
          format: int64
          type: integer
        isEnabled:
          description: YbaApi Internal Whether master tablet load balancer is enabled
          type: boolean
        isIdle:
          description: YbaApi Internal Whether master tablet load balancer is inactive
          type: boolean
      required:
      - isEnabled
      type: object
    CloudSpecificInfo_2:
      description: Node information reported by the cloud provider
      example:
        mount_roots: mount_roots
        kubernetesNamespace: kubernetesNamespace
        public_ip: public_ip
        secondary_subnet_id: secondary_subnet_id
        private_dns: private_dns
        useTimeSync: true
        kubernetesPodName: kubernetesPodName
        root_volume: root_volume
        secondary_private_ip: secondary_private_ip
        private_ip: private_ip
        cloud: cloud
        lun_indexes:
        - 6
        - 6
        assignPublicIP: true
        az: az
        subnet_id: subnet_id
        public_dns: public_dns
        region: region
        instance_type: instance_type
      properties:
        assignPublicIP:
          description: True if the node has a public IP address assigned
          type: boolean
        az:
          description: The node's availability zone
          type: string
        cloud:
          description: The node's cloud provider
          type: string
        instance_type:
          description: The node's instance type
          type: string
        kubernetesNamespace:
          description: Kubernetes namespace
          type: string
        kubernetesPodName:
          description: Pod name in Kubernetes
          type: string
        lun_indexes:
          description: Mounted disks LUN indexes
          items:
            format: int32
            type: integer
          type: array
        mount_roots:
          description: Mount roots
          type: string
        private_dns:
          description: The node's private DNS
          type: string
        private_ip:
          description: The node's private IP address
          type: string
        public_dns:
          description: The node's public DNS name
          type: string
        public_ip:
          description: The node's public IP address
          type: string
        region:
          description: The node's region
          type: string
        root_volume:
          description: Root volume ID or name
          type: string
        secondary_private_ip:
          description: Secondary Private IP
          type: string
        secondary_subnet_id:
          description: Secondary Subnet IP
          type: string
        subnet_id:
          description: ID of the subnet on which this node is deployed
          type: string
        useTimeSync:
          description: True if `use time sync` is enabled
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API key obtained from the YugabyteDB Aeon UI under User Profile > API Keys. Pass the key as a Bearer token in the Authorization header.
definitions:
  MastersList:
    properties:
      masters:
        items:
          $ref: '#/definitions/MasterNode'
        type: array
    required:
    - masters
    type: object
  CloudSpecificInfo:
    description: Node information reported by the cloud provider
    properties:
      assignPublicIP:
        description: True if the node has a public IP address assigned
        type: boolean
      az:
        description: The node's availability zone
        type: string
      cloud:
        description: The node's cloud provider
        type: string
      instance_type:
        description: The node's instance type
        type: string
      mount_roots:
        description: Mount roots
        type: string
      private_dns:
        description: The node's private DNS
        type: string
      private_ip:
        description: The node's private IP address
        type: string
      public_dns:
        description: The node's public DNS name
        type: string
      public_ip:
        description: The node's public IP address
        type: string
      region:
        description: The node's region
        type: string
      secondary_private_ip:
        description: Secondary Private IP
        type: string
      secondary_subnet_id:
        description: Secondary Subnet IP
        type: string
      subnet_id:
        description: ID of the subnet on which this node is deployed
        type: string
      useTimeSync:
        description: True if `use time sync` is enabled
        type: boolean
    type: object
  MasterNode:
    properties:
      cloudInfo:
        $ref: '#/definitions/CloudSpecificInfo'
      masterRpcPort:
        format: int32
        type: integer
    required:
    - cloudInfo
    - masterRpcPort
    type: object
  DummyBody:
    description: Dummy value to work around platform bug PLAT-2076
    properties:
      dummy:
        format: int32
        type: integer
    type: object
externalDocs:
  description: YugabyteDB Aeon REST API Documentation
  url: https://docs.yugabyte.com/stable/yugabyte-cloud/managed-automation/managed-api/
